### ISSUE TITLE
How to override theme CSS?

### ISSUE THREAD

**Issue by farazr** [basvandenberg/angular2-select#40]
I'm trying to remove the border around the input field but I can't seem to get my component's CSS to override that of `angular2-select`'s.

My component is defined like so:

```javascript
@Component({
  selector: 'app-campaign-create',
  templateUrl: 'campaign-create.component.html',
  styleUrls: ['campaign-create.component.css']
})
```

And in my `campaign-create.component.css` I'm tried a variation of the following:

```css
.select2-container--default .select2-selection--multiple {
  border: none;
}

.select2-container--default .select2-selection--single {
  border: none;
}

.select2-container--default {
  border: none;
}
```

In my HTML, I'm using the "default" theme:

```html
<ng-select
  class="form-control"
  [options]="options"
  multiple="true"
  placeholder="Select one or more vendors"
  [allowClear]="true"
  theme="default">
</ng-select>
```

But nothing seems to remove the border around input field.

Any advice?

Edit: Here's a screenshot showing what I get and what I want -- http://imgur.com/a/yB8zu
